# Generated by: Dmitry Stadub

@{

    ModuleVersion = '1.0.0'
        
    # ID used to uniquely identify this module
    GUID = 'b25d1196-1c95-47b4-8add-1415af66c318'
    
    # Author of this module
    Author = 'Dmitry Stadub'
    
    # Company or vendor of this module
    CompanyName = ''
    
    # Copyright statement for this module
    Copyright = '(c) Dmitry Stadub. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'Powershell Pipe filtering functions.
       Full documentation at the Github: https://github.com/stadub/PowershellScripts/tree/master/Shared-Functions/Pipe
    '
    NestedModules = @('Limit-First.ps1','Limit-Last.ps1', 'Hide-Out.ps1', 'Limit-Items.ps1', 'Where-Type.ps1', 'Skip-Items.ps1', 'Aliases.ps1')
    #RootModule = "Base64String.psm1"
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('*')
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @('Limit-First', 'Limit-Last', 'Hide-Out', 'Limit-Items', 'Where-Type', 'Skip-Items')
    
    # Variables to export from this module
    VariablesToExport = '*'
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @('*')
        
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('filter','pipe', 'first','last', 'Suppress', 'type')
    
            # A URL to the license for this module.
            LicenseUri = 'http://opensource.org/licenses/MIT'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/stadub/PowershellScripts/tree/master/Shared-Functions/Pipe'
    
            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/stadub/PowershellScripts/master/Shared-Functions/Pipe/Assets/Icon.ico'
    
            # ReleaseNotes of this module
            ReleaseNotes = '
                * Add url safe base 64 endcodding
            '
    
        }
    
    }
    

    HelpInfoURI = 'https://github.com/stadub/PowershellScripts/tree/master/Shared-Functions/Pipe/README.md'
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
    
    }
    
    